spring.application.name=result-viewer

server.port=${PORT:8085}

# MySQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/jdbc}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Show SQL Queries in Console
spring.jpa.show-sql=true

# Format SQL
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Spring Security
spring.security.user.name=${SPRING_SECURITY_USER_NAME:user}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:user}

# Error show in console
logging.level.org.springframework.security=DEBUG